# Generated by Django 3.0.5 on 2020-11-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmember',
            name='event_name',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='cmember',
            name='team_name',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
