# Generated by Django 3.0.5 on 2020-11-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201119_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ctask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('member_id', models.IntegerField()),
                ('task_title', models.CharField(max_length=1000)),
                ('task_description', models.CharField(max_length=10000)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
