# Generated by Django 3.0.5 on 2020-11-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201121_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmember',
            name='username',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='ctask',
            name='username',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
